spring.application.name=lf8-starter
spring.datasource.url=jdbc:postgresql://localhost:5433/lf8_starter
spring.datasource.username=lf8_starter
spring.datasource.password=geheim
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.mvc.problemdetails.enabled=true
server.error.include-stacktrace=never
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:9001/default/jwks
employee-service.url=http://localhost:8089
springdoc.swagger-ui.path=/swagger
